import type { Skill, SkillCategory } from "@/lib/types";

type Seed = Omit<Skill, "source"> & { source?: Skill["source"] };

const curated: Seed[] = [
  {
    id: "jcode",
    name: "Jcode harness",
    repo: "1jehuang/jcode",
    description:
      "RAM-efficient agent harness: semantic skill injection, swarm, memory graph, and a tight tool loop.",
    category: "harness",
    tags: ["harness", "swarm", "memory", "tools", "agent loop"],
    trigger: "agent harness tools swarm loop jcode coding",
    source: "builtin",
    stars: 19700,
  },
  {
    id: "minicpm-litert",
    name: "MiniCPM5 LiteRT",
    repo: "OpenBMB/MiniCPM",
    description:
      "On-device MiniCPM5-2B via LiteRT-LM. INT4 blockwise-32 + OCTAV, INT8 embeddings. Android CPU/GPU/NPU.",
    category: "runtime",
    tags: ["minicpm", "litert", "android", "quant", "tpu"],
    trigger: "model convert quantize litert android on-device minicpm",
    source: "builtin",
  },
  {
    id: "circuit",
    name: "Circuit screens",
    repo: "slackhq/circuit",
    description:
      "Compose-driven Presenter + UI + Screen architecture used for Sable's Android navigation model.",
    category: "android",
    tags: ["android", "compose", "circuit", "architecture"],
    trigger: "android compose navigation presenter screen",
    source: "builtin",
    stars: 1852,
  },
  {
    id: "foundry",
    name: "Foundry build",
    repo: "slackhq/foundry",
    description: "Gradle/IntelliJ Android build tooling. Used as the reference build graph for the native module.",
    category: "android",
    tags: ["android", "gradle", "foundry"],
    trigger: "android gradle build foundry",
    source: "builtin",
  },
  {
    id: "keeper",
    name: "Keeper R8",
    repo: "slackhq/keeper",
    description: "Infers Proguard/R8 keep rules so LiteRT JNI and NNAPI delegates survive shrinking.",
    category: "android",
    tags: ["android", "r8", "proguard", "keeper"],
    trigger: "r8 proguard shrink android keep rules",
    source: "builtin",
  },
  {
    id: "plan-manager",
    name: "Plan manager",
    repo: "yurihbm/opencode-plan-manager",
    description: "Plan management tools so coding agents keep a live, editable task graph.",
    category: "harness",
    tags: ["plan", "opencode", "tasks"],
    trigger: "plan tasks steps checklist",
    stars: 15,
  },
  {
    id: "workaholic",
    name: "Workaholic",
    repo: "RoderickQiu/opencode-workaholic",
    description: "Stops the agent from ending a task early. Pairs with plans.",
    category: "harness",
    tags: ["persistence", "plans"],
    trigger: "finish complete premature stop keep going",
    stars: 12,
  },
  {
    id: "snip",
    name: "Snip",
    repo: "VincentHardouin/opencode-snip",
    description: "Prefix shell output with snip to cut tokens from tool traces.",
    category: "runtime",
    tags: ["tokens", "shell"],
    trigger: "tokens compress shell output",
    stars: 142,
  },
  {
    id: "canvas",
    name: "OpenCode canvas",
    repo: "mailshieldai/opencode-canvas",
    description: "Interactive canvases: calendars, documents, booking boards.",
    category: "design",
    tags: ["canvas", "ui"],
    trigger: "canvas calendar document board ui",
    stars: 76,
  },
  {
    id: "harness-memory",
    name: "Harness memory",
    repo: "smc2315/harness-memory",
    description: "Project memory layer for coding harnesses. Durable facts across sessions.",
    category: "memory",
    tags: ["memory", "harness"],
    trigger: "remember memory preference project",
    stars: 19,
  },
  {
    id: "hiai",
    name: "HiAI orchestration",
    repo: "HiAi-gg/hiai-opencode",
    description: "Multi-agent slots, hooks, memory search, LSP diagnostics, completion controller.",
    category: "swarm",
    tags: ["multi-agent", "hooks", "lsp"],
    trigger: "orchestrate multi agent slots hooks lsp",
    stars: 17,
  },
  {
    id: "magic-context",
    name: "Magic context",
    repo: "cortexkit/magic-context",
    description: "Self-managing long memory. One session for life — the hippocampus for agents.",
    category: "memory",
    tags: ["memory", "context", "hippocampus"],
    trigger: "long context memory session lifetime",
    stars: 2113,
  },
  {
    id: "morph",
    name: "Morph fast apply",
    repo: "JRedeker/opencode-morph-fast-apply",
    description: "10x faster code edits with lazy markers. No MCP server.",
    category: "code",
    tags: ["edit", "apply", "code"],
    trigger: "edit apply patch code change",
    stars: 172,
  },
  {
    id: "shepherd",
    name: "Shepherd traces",
    repo: "shepherd-agents/shepherd",
    description: "Reversible Git-like traces of agent runs. Fork, replay, revert.",
    category: "harness",
    tags: ["trace", "replay", "git"],
    trigger: "trace replay revert fork run history",
    stars: 2410,
  },
  {
    id: "short-term",
    name: "Short-term memory",
    repo: "andrejtonev/opencode-short-term-memory",
    description: "Keeps user instructions and preferences alive across a long session.",
    category: "memory",
    tags: ["memory", "preferences"],
    trigger: "remember what I said preference instruction",
    stars: 9,
  },
  {
    id: "throughput",
    name: "Throughput",
    repo: "Howardzhangdqs/opencode-throughput",
    description: "Throughput instrumentation for OpenCode runs.",
    category: "runtime",
    tags: ["perf", "throughput"],
    trigger: "speed throughput latency tokens per second",
    stars: 28,
  },
  {
    id: "plan-annotator",
    name: "Plan annotator",
    repo: "ndom91/open-plan-annotator",
    description: "Local-first agent plan annotator.",
    category: "harness",
    tags: ["plan", "annotate"],
    trigger: "annotate plan review steps",
    stars: 94,
  },
  {
    id: "bg-agents",
    name: "Background agents",
    repo: "kdcokenny/opencode-background-agents",
    description: "Async delegation with context persistence. Claude Code-style background agents.",
    category: "swarm",
    tags: ["background", "async", "delegate"],
    trigger: "background async delegate later",
    stars: 387,
  },
  {
    id: "swarm",
    name: "OpenCode swarm",
    repo: "ZaxbyHub/opencode-swarm",
    description: "Hub-and-spoke swarm: architect, SME consult, generate, QA review.",
    category: "swarm",
    tags: ["swarm", "architect", "qa"],
    trigger: "swarm team parallel architect qa",
    stars: 469,
  },
  {
    id: "manage-skills",
    name: "ManageSkills",
    repo: "Randroids-Dojo/ManageSkills",
    description: "Skill manager for installing, enabling, and routing agent skills.",
    category: "harness",
    tags: ["skills", "manager"],
    trigger: "install skill enable disable catalog",
    stars: 4,
  },
  {
    id: "announcer",
    name: "Model announcer",
    repo: "ramarivera/opencode-model-announcer",
    description: "Announces the active model and runtime so the user always knows what is answering.",
    category: "runtime",
    tags: ["model", "status"],
    trigger: "which model runtime accelerator",
    stars: 35,
  },
  {
    id: "sessions",
    name: "Sessions",
    repo: "malhashemi/opencode-sessions",
    description: "Session management with multi-agent collaboration support.",
    category: "harness",
    tags: ["session", "collab"],
    trigger: "session resume list conversations",
    stars: 176,
  },
  {
    id: "synced",
    name: "Synced config",
    repo: "iHildy/opencode-synced",
    description: "Sync global agent config between machines.",
    category: "harness",
    tags: ["sync", "config"],
    trigger: "sync config machines settings",
    stars: 151,
  },
  {
    id: "papers",
    name: "Research papers",
    repo: "saim-x/opencode-research-papers",
    description: "Search arXiv and OpenAlex with recency, citation, and relevance filters.",
    category: "research",
    tags: ["arxiv", "papers", "research"],
    trigger: "paper arxiv research cite paper",
    stars: 18,
  },
  {
    id: "typeui",
    name: "TypeUI",
    repo: "bergside/typeui",
    description: "Build better UI with AI. Typed interface generation.",
    category: "design",
    tags: ["ui", "type", "frontend"],
    trigger: "ui design frontend interface",
    stars: 1925,
  },
  {
    id: "liter-llm",
    name: "Liter LLM",
    repo: "xberg-io/liter-llm",
    description: "Universal LLM client — 163 providers, Rust core, 14 language bindings.",
    category: "runtime",
    tags: ["client", "providers"],
    trigger: "provider api client openai compatible",
    stars: 254,
  },
  {
    id: "makefaster",
    name: "Make Faster",
    repo: "jjcm/makefaster",
    description: "Website performance tools and site leaderboard.",
    category: "runtime",
    tags: ["perf", "web"],
    trigger: "performance web vitals faster",
    stars: 137,
  },
  {
    id: "reverse-skill",
    name: "Reverse skill",
    repo: "zhaoxuya520/reverse-skill",
    description:
      "Authorized reverse engineering / pentest skill router. On-demand toolchain + evolving knowledge base.",
    category: "security",
    tags: ["reverse", "security", "pentest"],
    trigger: "reverse engineer binary security authorized pentest",
    stars: 35946,
  },
  {
    id: "agenttrail",
    name: "Agenttrail",
    repo: "sodiumsun/agenttrail",
    description: "Local observability for coding agents. Map + 3D kitchen of tasks and roles.",
    category: "harness",
    tags: ["observe", "trace", "map"],
    trigger: "observe trace visualize agent activity",
    stars: 664,
  },
  {
    id: "spiderfoot",
    name: "SpiderFoot",
    repo: "smicallef/spiderfoot",
    description: "Automates OSINT for threat intelligence and attack-surface mapping.",
    category: "osint",
    tags: ["osint", "recon"],
    trigger: "osint recon threat surface domain",
    stars: 22112,
  },
  {
    id: "archify",
    name: "Archify",
    repo: "tt-a1i/archify",
    description:
      "Architecture, workflow, sequence, data-flow, and lifecycle diagrams as self-contained HTML.",
    category: "design",
    tags: ["architecture", "diagram", "mermaid"],
    trigger: "architecture diagram sequence flowchart mermaid",
    stars: 62643,
  },
  {
    id: "code-graph-rag",
    name: "Code graph RAG",
    repo: "vitali87/code-graph-rag",
    description: "Knowledge-graph RAG over a monorepo. Query, understand, and edit multi-language code.",
    category: "code",
    tags: ["rag", "graph", "codebase"],
    trigger: "codebase rag graph repo understand edit",
    stars: 5135,
  },
  {
    id: "semantica",
    name: "Semantica",
    repo: "semantica-agi/semantica",
    description: "Graph-native infrastructure for context and accountable AI systems.",
    category: "memory",
    tags: ["graph", "context", "accountable"],
    trigger: "knowledge graph accountable context",
    stars: 12898,
  },
  {
    id: "gigatoken",
    name: "Gigatoken",
    repo: "marcelroed/gigatoken",
    description: "Language-model tokenization at GB/s. Fast tokenizer for on-device prefill.",
    category: "runtime",
    tags: ["tokenizer", "perf"],
    trigger: "tokenize tokenizer prefill speed",
    stars: 4096,
  },
  {
    id: "wigolo",
    name: "Wigolo",
    repo: "KnockOutEZ/wigolo",
    description: "Local-first search, fetch, crawl, and research for coding agents. No API keys.",
    category: "research",
    tags: ["search", "crawl", "local"],
    trigger: "search web crawl fetch research local",
    stars: 5259,
  },
  {
    id: "openspace",
    name: "OpenSpace",
    repo: "HKUDS/OpenSpace",
    description: "Skill management layer for AI agents. Install, route, version skills.",
    category: "harness",
    tags: ["skills", "registry"],
    trigger: "skill manager registry install route",
    stars: 7667,
  },
  {
    id: "cognetivy",
    name: "Cognetivy",
    repo: "meitarbe/cognetivy",
    description: "Open-source state layer. Structured, traceable agent runs and collections.",
    category: "harness",
    tags: ["state", "runs", "trace"],
    trigger: "state run event collection workspace",
    stars: 783,
  },
  {
    id: "headroom",
    name: "Headroom",
    repo: "headroomlabs-ai/headroom",
    description: "Compress tool outputs, logs, files, and RAG chunks before they hit the model.",
    category: "runtime",
    tags: ["compress", "tokens"],
    trigger: "compress tokens context window headroom",
    stars: 72199,
  },
  {
    id: "heretic",
    name: "Heretic",
    repo: "p-e-w/heretic",
    description: "Automatic refusal/censorship removal for local language models you host.",
    category: "runtime",
    tags: ["uncensor", "local"],
    trigger: "refusal uncensored local model",
    stars: 31431,
  },
  {
    id: "understand-anything",
    name: "Understand Anything",
    repo: "Egonex-AI/Understand-Anything",
    description: "Turn any codebase into an interactive knowledge graph you can ask questions about.",
    category: "code",
    tags: ["graph", "understand", "code"],
    trigger: "understand code graph explore ask repo",
    stars: 82846,
  },
  {
    id: "opentui",
    name: "OpenTUI",
    repo: "anomalyco/opentui",
    description: "Library to build terminal user interfaces. Jcode's TUI cousin.",
    category: "design",
    tags: ["tui", "terminal"],
    trigger: "terminal tui cli interface",
    stars: 13307,
  },
  {
    id: "ez-tree",
    name: "ez-tree",
    repo: "dgreenheck/ez-tree",
    description: "Procedural tree generator. Useful for spatial / generative skills.",
    category: "design",
    tags: ["procedural", "tree"],
    trigger: "tree procedural generate mesh",
    stars: 1633,
  },
  {
    id: "opencove",
    name: "OpenCove",
    repo: "DeadWaveWave/opencove",
    description: "Infinite canvas for agents, tasks, knowledge, and research.",
    category: "design",
    tags: ["canvas", "workspace"],
    trigger: "canvas workspace infinite board research",
    stars: 1588,
  },
  {
    id: "terrarium",
    name: "KohakuTerrarium",
    repo: "Kohaku-Lab/KohakuTerrarium",
    description: "Compose self-contained agents and multi-agent teams with built-in tools.",
    category: "swarm",
    tags: ["multi-agent", "compose"],
    trigger: "compose team agents terrarium",
    stars: 500,
  },
  {
    id: "opensquilla",
    name: "OpenSquilla",
    repo: "TokenRhythm/opensquilla",
    description: "Token-efficient agent: same budget, higher intelligence density.",
    category: "runtime",
    tags: ["tokens", "density"],
    trigger: "token efficient density budget",
    stars: 7020,
  },
  {
    id: "iii",
    name: "iii",
    repo: "iii-hq/iii",
    description: "Compose, extend, and observe every service in real time.",
    category: "harness",
    tags: ["observe", "compose", "services"],
    trigger: "observe services compose extend realtime",
    stars: 18701,
  },
];

export const SKILL_CATALOG: Skill[] = curated.map((s) => ({
  ...s,
  source: s.source ?? "curated",
}));

export const CATEGORY_LABEL: Record<SkillCategory, string> = {
  harness: "Harness",
  memory: "Memory",
  swarm: "Swarm",
  code: "Code",
  research: "Research",
  security: "Security",
  runtime: "Runtime",
  design: "Design",
  osint: "OSINT",
  android: "Android",
};

export const DEFAULT_INSTALLED = [
  "jcode",
  "minicpm-litert",
  "circuit",
  "harness-memory",
  "openspace",
  "headroom",
  "archify",
  "magic-context",
];
